// app/pages/create-point/index.vue
<script setup>
// filepath: /home/gabriel/Documentos/projetos/recycling/app/pages/create-point/index.vue

import { ref, reactive, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
// import { useLeaflet } from '@vue-leaflet/vue-leaflet'
import axios from 'axios'
// import { api } from '~/services/api'
import logo from '../../../public/assets/logo.svg'
import loadingLogo from '../../../public/assets/loading-logo.svg'
import successImage from '../../../public/assets/success.svg'

const items = ref([])
const ufs = ref([])
const cities = ref([])
const selectedPosition = ref([0, 0])
const initialPosition = ref([0, 0])
const isLoading = ref(true)
const showSuccessModal = ref(false)

const inputData = reactive({
  name: '',
  email: '',
  whatsapp: '',
})

const selectedUf = ref('0')
const selectedCity = ref('0')
const selectedItems = ref([])
const selectedFile = ref(null)

const router = useRouter()

onMounted(() => {
  // api.get('items').then((response) => {
    // items.value = response.data.serializedItems
  // })

  axios
    .get('https://servicodados.ibge.gov.br/api/v1/localidades/estados')
    .then((response) => {
      ufs.value = response.data.map((uf) => uf.sigla)
    })

  navigator.geolocation.getCurrentPosition(
    (position) => {
      const { latitude, longitude } = position.coords
      initialPosition.value = [latitude, longitude]
      isLoading.value = false
    },
    () => {
      initialPosition.value = [-23.1799079, -45.8253392]
      isLoading.value = false
    }
  )
})

watch(selectedUf, (newUf) => {
  if (newUf === '0') return
  axios
    .get(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/${newUf}/municipios`)
    .then((response) => {
      cities.value = response.data.map((city) => city.nome)
    })
})

function handleSelectUf(event) {
  selectedUf.value = event.target.value
}

function handleSelectCity(event) {
  selectedCity.value = event.target.value
}

function handleInputChange(event) {
  const { name, value } = event.target
  inputData[name] = value
}

function handleSelectItem(id) {
  const alreadySelected = selectedItems.value.includes(id)
  if (alreadySelected) {
    selectedItems.value = selectedItems.value.filter((item) => item !== id)
  } else {
    selectedItems.value.push(id)
  }
}

function handleMapClick(event) {
  selectedPosition.value = [event.latlng.lat, event.latlng.lng]
}

async function handleSubmit(event) {
  event.preventDefault()

  const { name, email, whatsapp } = inputData
  const uf = selectedUf.value
  const city = selectedCity.value
  const [latitude, longitude] = selectedPosition.value
  const itemsIds = selectedItems.value

  if (!name || !email || !whatsapp || uf === '0' || city === '0' || latitude === 0 || longitude === 0 || items.value.length === 0) {
    alert('Por favor, preencha todos os campos obrigatórios.')
    return
  }

  const data = new FormData()
  data.append('name', name)
  data.append('email', email)
  data.append('whatsapp', whatsapp)
  data.append('uf', uf)
  data.append('city', city)
  data.append('latitude', String(latitude))
  data.append('longitude', String(longitude))
  itemsIds.forEach((item) => data.append('itemsIds[]', item))

  if (selectedFile.value) {
    data.append('image', selectedFile.value)
  }

  try {
    // await api.post('points', data)
    showSuccessModal.value = true
    setTimeout(() => {
      showSuccessModal.value = false
      router.push('/')
    }, 4000)
  } catch (error) {
    console.error('Erro ao cadastrar o ponto de coleta:', error)
    alert('Houve um erro ao cadastrar o ponto de coleta.')
  }
}
</script>

<template>
  <div id="page-create-point" class="max-w-5xl mx-auto">
    <header class="mt-12 flex justify-between items-center">
      <img :src="logo" alt="Recycling Logo" />
      <nuxt-link to="/" class="text-primary font-bold flex items-center">
        <i class="fi fi-arrow-left mr-2"></i> Voltar para home
      </nuxt-link>
    </header>

    <div v-if="isLoading" class="flex flex-col items-center justify-center h-screen">
      <img :src="loadingLogo" alt="Carregando" />
      <span class="mt-4 text-lg">Carregando app...</span>
    </div>

    <form v-else @submit="handleSubmit" class="bg-white p-8 rounded-lg shadow-md mt-8">
      <h1 class="text-3xl font-bold mb-8">Cadastro do ponto de coleta</h1>

      <dropzone @file-uploaded="(file) => (selectedFile = file)" />

      <fieldset class="mt-8">
        <legend class="text-xl font-semibold mb-4">Dados</legend>
        <div class="mb-4">
          <label for="name" class="block text-sm font-medium">Nome da Entidade</label>
          <input
            type="text"
            id="name"
            name="name"
            v-model="inputData.name"
            class="w-full p-3 border rounded"
          />
        </div>
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label for="email" class="block text-sm font-medium">E-mail</label>
            <input
              type="email"
              id="email"
              name="email"
              v-model="inputData.email"
              class="w-full p-3 border rounded"
            />
          </div>
          <div>
            <label for="whatsapp" class="block text-sm font-medium">Whatsapp</label>
            <input
              type="text"
              id="whatsapp"
              name="whatsapp"
              v-model="inputData.whatsapp"
              class="w-full p-3 border rounded"
            />
          </div>
        </div>
      </fieldset>

      <fieldset class="mt-8">
        <legend class="text-xl font-semibold mb-4">Endereço</legend>
        <span class="block text-sm mb-4">Selecione o endereço no mapa</span>
        <l-map
          :zoom="15"
          :center="initialPosition"
          class="w-full h-96 rounded mb-4"
          @click="handleMapClick"
        >
          <l-tile-layer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
          <l-marker :lat-lng="selectedPosition" />
        </l-map>
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label for="uf" class="block text-sm font-medium">Estado (UF)</label>
            <select
              id="uf"
              v-model="selectedUf"
              class="w-full p-3 border rounded"
              @change="handleSelectUf"
            >
              <option value="0">Selecione uma UF</option>
              <option v-for="uf in ufs" :key="uf" :value="uf">{{ uf }}</option>
            </select>
          </div>
          <div>
            <label for="city" class="block text-sm font-medium">Cidade</label>
            <select
              id="city"
              v-model="selectedCity"
              class="w-full p-3 border rounded"
              @change="handleSelectCity"
            >
              <option value="0">Selecione uma cidade</option>
              <option v-for="city in cities" :key="city" :value="city">{{ city }}</option>
            </select>
          </div>
        </div>
      </fieldset>

      <fieldset class="mt-8">
        <legend class="text-xl font-semibold mb-4">Itens de Coleta</legend>
        <ul class="grid grid-cols-3 gap-4">
          <li
            v-for="item in items"
            :key="item.id"
            @click="handleSelectItem(item.id)"
            :class="{ 'border-green-500 bg-green-100': selectedItems.includes(item.id) }"
            class="p-4 border rounded cursor-pointer"
          >
            <img :src="item.image_url" :alt="item.title" class="w-full h-24 object-cover" />
            <span class="block mt-2 text-center">{{ item.title }}</span>
          </li>
        </ul>
      </fieldset>

      <button
        type="submit"
        class="mt-8 bg-primary text-white font-bold py-3 px-6 rounded hover:bg-green-600"
      >
        Cadastrar Ponto de Coleta
      </button>
    </form>

    <div
      v-if="showSuccessModal"
      class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center"
    >
      <div class="bg-white p-8 rounded-lg text-center">
        <img :src="successImage" alt="Sucesso" class="mx-auto mb-4" />
        <p class="text-xl font-bold">Cadastro concluído!</p>
      </div>
    </div>
  </div>
</template>

<style>
/* Adicione estilos globais ou específicos aqui, se necessário */
</style>

// src/pages/CreatePoint/index.tsx
import React, { useEffect, useState, ChangeEvent, FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { FiArrowLeft } from 'react-icons/fi'
import { MapContainer, TileLayer, Marker, useMapEvent } from 'react-leaflet'
import { LeafletMouseEvent } from 'leaflet'
import axios, { AxiosResponse } from 'axios'
import { api } from '../../services/api'
import logo from '../../assets/logo.svg'
import loadingLogo from '../../assets/loading-logo.svg'
import successIcon from '../../assets/success.svg'

import './styles.css'
import Dropzone from '../../components/drop-zone'

interface Item {
  id: string,
  title: string,
  image_url: string
}

interface IBGEUFResponse {
  sigla: string
}

interface IBGECityResponse {
  nome: string
}

type MapEventsHandlerProps = {
  handleMapClick: (event: LeafletMouseEvent) => void;
};

const CreatePoint = () => {
  const [items, setItems] = useState<Item[]>([])
  const [ufs, setUfs] = useState<string[]>([])
  const [cities, setCities] = useState<string[]>([])
  const [selectedPosition, setSelectedPosition] = useState<[number, number]>([0, 0])
  const [initialPosition, setInitialPosition] = useState<[number, number]>([0, 0])

  const [inputData, setInputData] = useState({
    name: '',
    email: '',
    whatsapp: '',
  })

  const [selectedUf, setSelectedUf] = useState('0')
  const [selectedCity, setSelectedCity] = useState('0')
  const [isLoading, setIsLoading] = useState(true);
  const [selectedItems, setSelectedItems] = useState<string[]>([])
  const [selectedFile, setSelectedFile] = useState<File>()
  const [showSuccessModal, setShowSuccessModal] = useState(false);

  const navigate = useNavigate()

  useEffect(() => {
    api.get('items').then((response: AxiosResponse) => {
      setItems(response.data.serializedItems)
    })
  }, [])

  useEffect(() => {
    axios
      .get<IBGEUFResponse[]>('https://servicodados.ibge.gov.br/api/v1/localidades/estados')
      .then((response) => {
        const ufInitials = response.data.map((uf) => uf.sigla)

        setUfs(ufInitials)
      })
  }, [])

  useEffect(() => {
    if (selectedUf === '0') {
      return
    }
    axios
      .get<IBGECityResponse[]>(`https://servicodados.ibge.gov.br/api/v1/localidades/estados/${selectedUf}/municipios`)
      .then((response) => {
        const cityNames = response.data.map((city) => city.nome)

        setCities(cityNames)
      })

  }, [selectedUf])

  useEffect(() => {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        const { latitude, longitude } = position.coords
        setInitialPosition([latitude, longitude])
        setIsLoading(false)
      },
      (error) => {
        console.error("Erro ao obter a localização: ", error)
        setInitialPosition([-23.1799079, -45.8253392])
        setIsLoading(false)
      }
    )
  }, [])

  function handleSelectUf(event: ChangeEvent<HTMLSelectElement>) {
    const uf = event.target.value

    setSelectedUf(uf)
  }

  function handleSelectCity(event: ChangeEvent<HTMLSelectElement>) {
    const city = event.target.value

    setSelectedCity(city)
  }

  function handleInputChange(event: ChangeEvent<HTMLInputElement>) {
    const { name, value } = event.target

    setInputData({ ...inputData, [name]: value })
  }

  function handleSelectItem(id: string) {
    const alreadySelected = selectedItems.findIndex(item => item === id)

    if (alreadySelected >= 0) {
      const filteredItems = selectedItems.filter(item => item !== id)

      setSelectedItems(filteredItems)
    } else {
      setSelectedItems([...selectedItems, id])
    }
  }

  const handleMapClick = (event: LeafletMouseEvent) => {
    setSelectedPosition([
      event.latlng.lat,
      event.latlng.lng
    ])
  }

  const MapEventsHandler: React.FC<MapEventsHandlerProps> = ({ handleMapClick }) => {
    useMapEvent(
      'click', (event) => handleMapClick(event)
    )
    return null
  }

  async function handleSubmit(event: FormEvent) {
    event.preventDefault()

    const { name, email, whatsapp } = inputData
    const uf = selectedUf
    const city = selectedCity
    const [latitude, longitude] = selectedPosition
    const itemsIds = selectedItems

    if (!name || !email || !whatsapp || uf === '0' || city === '0' || latitude === 0 || longitude === 0 || items.length === 0) {
      alert('Por favor, preencha todos os campos obrigatórios.')
      return
    }

    const data = new FormData()
    data.append('name', name);
    data.append('email', email);
    data.append('whatsapp', whatsapp);
    data.append('uf', uf);
    data.append('city', city);
    data.append('latitude', String(latitude));
    data.append('longitude', String(longitude));
    itemsIds.forEach(item => data.append('itemsIds[]', item));

    if (selectedFile) {
      data.append('image', selectedFile)
    }

    try {
      await api.post('points', data)
      setShowSuccessModal(true); // Exibir o modal de sucesso
      setTimeout(() => {
        setShowSuccessModal(false); // Esconder o modal após 3 segundos
        navigate(-1);
      }, 4000);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error('Axios error:', error.response?.data)
        alert('Houve um erro ao cadastrar o ponto de coleta: ' + (error.response?.data.message || 'Erro desconhecido'))
      } else {
        console.error('Unexpected error:', error)
        alert('Ocorreu um erro inesperado')
      }
    }
  }

  if (isLoading) {
    return (
      <div className='loadingLogo'>
        <img src={loadingLogo} alt="Logo do Recycling" />
        <span>Carregando app...</span>
      </div>
    )
  }

  return (
    <div id="page-create-point">
      <header>
        <img src={logo} alt="recycling logo" />
        <Link to='/'>
          <FiArrowLeft />
          Voltar para home
        </Link>
      </header>
      {showSuccessModal && (
        <div className="modal-container">
          <div className="modal-content">
            <img src={successIcon} alt="Ícone de sucesso" />
            <p>Cadastro concluído!</p>
          </div>
        </div>
      )}
      <form onSubmit={handleSubmit}>
        <h1>Cadastro do <br /> ponto de Coleta</h1>

        <Dropzone onFileUploaded={setSelectedFile} />


        <fieldset>
          <legend>
            <h2>Dados</h2>
          </legend>

          <div className="field">
            <label htmlFor="name">Nome da Entidade</label>
            <input
              type="text"
              name="name"
              id="name"
              onChange={handleInputChange}
            />
          </div>

          <div className="field-group">
            <div className="field">
              <label htmlFor="email">E-mail</label>
              <input
                type="email"
                name="email"
                id="email"
                onChange={handleInputChange}
              />
            </div>
            <div className="field">
              <label htmlFor="whatsapp">Whatsapp</label>
              <input
                type="text"
                name="whatsapp"
                id="whatsapp"
                onChange={handleInputChange}
              />
            </div>
          </div>
        </fieldset>

        <fieldset>
          <legend>
            <h2>Endereço</h2>
            <span>Selecione o endereço no mapa</span>
          </legend>
          <MapContainer center={initialPosition} zoom={15} className={showSuccessModal ? "map-container modal-open" : "map-container"} >
            <TileLayer
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            <MapEventsHandler handleMapClick={handleMapClick} />
            <Marker position={selectedPosition} />
          </MapContainer>

          <div className="field-group">
            <div className="field">
              <label htmlFor="uf">Estado (uf)</label>
              <select
                name="uf"
                id="uf"
                value={selectedUf}
                onChange={handleSelectUf}
              >
                <option value="0">Selecione uma UF</option>
                {ufs.map(uf => (
                  <option key={uf} value={uf}>{uf}</option>
                ))}
              </select>
            </div>
            <div className="field">
              <label htmlFor="city">Cidade</label>
              <select
                name="city"
                id="city"
                value={selectedCity}
                onChange={handleSelectCity}
              >
                <option value="0">Selecione uma cidade</option>
                {cities.map(city => (
                  <option key={city} value={city}>{city}</option>
                ))}
              </select>
            </div>
          </div>
        </fieldset>

        <fieldset>
          <legend>
            <h2>Itens de Coleta</h2>
            <span>Selecione um ou mais itens abaixo</span>
          </legend>

          <ul className='items-grid'>
            {items.map(item => (
              <li
                key={item.id}
                onClick={() => handleSelectItem(item.id)}
                className={selectedItems.includes(item.id) ? 'selected' : ''}
              >
                <img src={item.image_url} alt={`Imagem do item ${item.title}`} />
                <span>{item.title}</span>
              </li>
            ))}
          </ul>
        </fieldset>

        <button type="submit">Cadastrar Ponto de Coleta</button>
      </form>
    </div>
  )
}

export default CreatePoint

// 42
